f = open("../data/finemap.txt", "r")
a = [x.strip().split(" ") for x in f.readlines()]
f.close()
SIM = list(range(100))
scenario = [x[0] + "_" + x[1] + "_" + x[3] for x in a]
minvar = 0
maxvar = 0.5

rule all:
	input:
		expand("../data/scratch/{scen}/polygenic.bed", scen=scenario),
		expand("../data/scratch/{scen}/{sim}.rdata", scen=scenario, sim=SIM),
		"../data/aggregate.rdata"


rule create_data:
	input:
		"../data/disc.bed",
		"../data/rep.bed",
		"../data/finemap.txt"
	output:
		"../data/scratch/{scen}/polygenic.bed"
	shell:
		"./create_data.sh {wildcards.scen}"


rule runsim:
	input:
		"../data/disc.bed",
		"../data/rep.bed",
		"../data/finemap.txt",
		"../data/scratch/{scen}/polygenic.bed"
	output:
		"../data/scratch/{scen}/{sim}.rdata"
	shell:
		"./analyse_data.sh {wildcards.scen} {wildcards.sim} {minvar} {maxvar}"


rule aggregate:
	input:
		expand("../data/scratch/{scen}/{sim}.rdata", scen=scenario, sim=SIM)
	output:
		"../data/aggregate.rdata"
	shell:
		"Rscript aggregate.r"
