f = open("../data/finemap.txt", "r")
a = [x.strip().split(" ") for x in f.readlines()]
f.close()
SIM1 = list(range(10000))
SIM2 = list(range(200))
SIM3 = list(range(100))
scenario = [x[0] + "_" + x[1] + "_" + x[3] for x in a]
scen0 = "MBNL1_rs67903230_rs13069559"
minvar = 0
maxvar = 0.5


rule all:
	input:
		expand("../data/scratch/{scen}/polygenic.bed", scen=scenario),
		expand("../data/scratch/{scen0}/{sim1}.scen1.rdata", scen0=scen0, sim1=SIM1),
		expand("../data/scratch/{scen}/{sim2}.scen2.rdata", scen=scenario, sim2=SIM2),
		expand("../data/scratch/{scen}/{sim3}.scen3.rdata", scen=scenario, sim3=SIM3),
		"../data/aggregate1.rdata",
		"../data/aggregate2.rdata",
		"../data/aggregate3.rdata"


rule create_data:
	input:
		"../data/disc.bed",
		"../data/rep.bed",
		"../data/finemap.txt"
	output:
		"../data/scratch/{scen}/polygenic.bed"
	shell:
		"./create_data.sh {wildcards.scen}"


rule runsim1:
	input:
		"../data/disc.bed",
		"../data/rep.bed",
		"../data/finemap.txt",
		"../data/scratch/{scen0}/polygenic.bed"
	output:
		"../data/scratch/{scen0}/{sim1}.scen1.rdata"
	shell:
		"./analyse_data_scen1.sh {wildcards.sim1} {minvar} {maxvar}"


rule aggregate1:
	input:
		expand("../data/scratch/{scen0}/{sim1}.scen1.rdata", scen0=scen0, sim1=SIM1)
	output:
		"../data/aggregate1.rdata"
	shell:
		"Rscript aggregate.r scen1.rdata ../data/aggregate1.rdata"


rule runsim2:
	input:
		"../data/disc.bed",
		"../data/rep.bed",
		"../data/finemap.txt",
		"../data/scratch/{scen}/polygenic.bed"
	output:
		"../data/scratch/{scen}/{sim2}.scen2.rdata"
	shell:
		"./analyse_data_scen2.sh {wildcards.scen} {wildcards.sim2} {minvar} {maxvar}"


rule aggregate2:
	input:
		expand("../data/scratch/{scen}/{sim2}.scen2.rdata", scen=scenario, sim2=SIM2)
	output:
		"../data/aggregate2.rdata"
	shell:
		"Rscript aggregate.r scen2.rdata ../data/aggregate2.rdata"


rule runsim3:
	input:
		"../data/disc.bed",
		"../data/rep.bed",
		"../data/finemap.txt",
		"../data/scratch/{scen}/polygenic.bed"
	output:
		"../data/scratch/{scen}/{sim3}.scen3.rdata"
	shell:
		"./analyse_data_scen3.sh {wildcards.scen} {wildcards.sim3}"


rule aggregate3:
	input:
		expand("../data/scratch/{scen}/{sim3}.scen3.rdata", scen=scenario, sim3=SIM3)
	output:
		"../data/aggregate3.rdata"
	shell:
		"Rscript aggregate.r scen3.rdata ../data/aggregate3.rdata"
