% grDevices::pdf.options(useDingbats = FALSE)
% require(knitr)
% opts_knit$set(concordance = TRUE)
% knit('report.Rnw', encoding='UTF-8')

\documentclass{article}
\usepackage{subfig}
\usepackage{rotating}

\begin{document}

\title{The effect of inbreeding on BMI and height}

\maketitle

<<initialise, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE>>=

read_chunk("~/repo/eQTL-2D/docs/replication_analysis/analyse_replication.R")

@


<<qqplots, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE, fig.cap="Q-Q plots of interaction p-values from replication dataset", fig.subcap=c("All signals", "Signals excluding 20 most significant replications"), out.width='.4\\linewidth'>>=

qqplot1
qqplot2

@


<<overlapplots, eval=TRUE, echo=FALSE, warning=FALSE, cache=TRUE, message=FALSE, fig.cap='Overlap in signals between replication datasets', fig.subcap=c('Bonferroni significance', '5\\% FDR significance'), out.width='.4\\linewidth'>>=

# Characterise overlap
# Significant in only Fehr, Significant in only EGCUT, Significant in both

# Make venn diagram

plot.new() 
grid.draw(bonf.venn)

plot.new() 
grid.draw(fdr.venn)

@

<<corpfull, eval=TRUE, echo=FALSE, warning=FALSE, cache=TRUE, fig.cap='Full genetic effects correlate between datasets (8d.f. p-values)', fig.subcap=c('All signals', 'Signals that surpass 5\\% FDR in both datasets'), out.width='.4\\linewidth'>>=


plotCor(pfull_all)
plotCor(pfull_f)

@

<<corpnest, eval=TRUE, echo=FALSE, warning=FALSE, cache=TRUE, fig.cap='Full genetic effects correlate between datasets (8d.f. p-values)', fig.subcap=c('All signals', 'Signals that surpass 5\\% FDR in both datasets'), out.width='.4\\linewidth'>>=

plotCor(pnest_all)
plotCor(pnest_f)

@

<<interactiontable, cache=TRUE, eval=TRUE, echo=FALSE, results='asis', size='tiny'>>=

print(xtable(bonf.tab, caption="The 20 most significant interaction terms from both replication sets. * denotes Bonferroni level significance in the named data set."), include.rownames=FALSE, latex.environments=c("center", "footnotesize"), floating.environment="sidewaystable")
@


\end{document}